dist: trusty
sudo: required

jobs:
  include:
    - stage: Docker Build
      script:
      - docker login -u="siomiz" -p="$DOCKER_PASSWORD"
      - docker build -t softethervpn .
      - docker tag softethervpn siomiz/softethervpn:travis-ci
      - docker push siomiz/softethervpn:travis-ci
    - stage: Test
      script:
      - docker run --rm siomiz/softethervpn:travis-ci echo "[Travis CI OK]"
    - script:
      - sudo bash tests/prepare-softethervpn.sh
      - sudo bash tests/prepare-ipsec.sh
      - sudo bash tests/test-ipsec.sh
    - script:
      - sudo bash tests/prepare-softethervpn.sh

