language: ruby

services:
  - docker

matrix:
  include:
    - name: CentOS
      env: BUILDFILE=Dockerfile
    - name: Alpine
      env: BUILDFILE=Dockerfile.alpine
    - name: Debian
      env: BUILDFILE=Dockerfile.debian
    - name: Ubuntu
      env: BUILDFILE=Dockerfile.ubuntu

script:
  - docker build -f ${BUILDFILE} -t softethervpn .
  - docker run softethervpn echo "[Travis CI OK]"
  - docker network create --subnet 172.18.0.0/16 test-ipsec
  - docker run -d --cap-add NET_ADMIN -e USERNAME=test -e PASSWORD=test --network test-ipsec --ip 172.18.0.3 softethervpn
  - sudo bash tests/prepare-ipsec.sh
  - sudo bash tests/test-ipsec.sh
