sudo: required

language: c

env:
  - BUILD_DIR=.

services:
  - docker

before_install:
  - docker build -t siomiz/softethervpn $BUILD_DIR
  - cd ${BUILD_DIR}/tests
  - bash ./prepare.sh

install: true

script:
  - docker run --cap-add NET_ADMIN -e USERNAME=test -e PASSWORD=test siomiz/softethervpn
  - bash ./ipsec.sh
