language: ruby

services:
  - docker

matrix:
  include:
    - name: CentOS
      env: BUILDFILE=Dockerfile
    - name: Alpine
      env: BUILDFILE=Dockerfile.alpine
    - name: Debian
      env: BUILDFILE=Dockerfile.debian
    - name: Ubuntu
      env: BUILDFILE=Dockerfile.ubuntu

script:
  - docker build -f ${BUILDFILE} .

