dist: trusty
sudo: required

jobs:
  include:
    - stage: Docker Build
      script:
      - docker build -t softethervpn .
    - stage: Test
      script:
      - docker run --rm softethervpn echo "[Travis CI OK]"
    - script:
      - docker network create test-ipsec
      - docker run -d --cap-add NET_ADMIN -e USERNAME=test -e PASSWORD=test --network test-ipsec softethervpn
      - sudo bash ./ipsec.sh

