sudo: required

language: c

env:
  - BUILD_DIR=.

services:
  - docker

before_install:
  - docker build -t siomiz/softethervpn $BUILD_DIR
  - cd ${BUILD_DIR}/tests
  - sudo bash ./prepare.sh

install: true

script:
  - docker run -d --cap-add NET_ADMIN -e USERNAME=test -e PASSWORD=test siomiz/softethervpn
  - sudo bash ./ipsec.sh
